apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
spec:
  selector:
    matchLabels:
      app: devopswebapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: venkatasykam/devopswebapp:1.0.13
        ports:
        - containerPort: 8080
