apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
spec:
  selector:
    matchLabels:
      app: devopswebapp
  replicas: 2 # Update the replicas from 2 to 5
  template:
    metadata:
      labels:
        app: devopswebapp
    spec:
      containers:
      - name: devopswebapp
        image: venkatasykam/devopswebapp:1.0.14 #Update the version from 1.0.13 to 1.0.14
        ports:
        - containerPort: 8080
