apiVersion: v1
kind: Service
metadata:
  name: devopswebapp
  namespace: default
  labels:
    app: devopswebapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30808
  selector:
    app: devopswebapp
